# Generated by Django 2.2 on 2020-05-14 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('cant_pag', models.IntegerField()),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('codAutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibl.Autor')),
            ],
        ),
    ]
