# Generated by Django 2.2 on 2020-05-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibl', '0002_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
